### ISSUE TITLE
Consider adding a denoising filter before segmentation

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/model_seg_ms_mp2rage#46]
Some denoising filters are quite powerful, and could potentially help during model training/testing. Eg:

```bash
sct_maths -i sub-P001_UNIT1.nii.gz -denoise 1 -o sub-P001_UNIT1_denoised.nii.gz 
```

![anim](https://user-images.githubusercontent.com/2482071/151209821-9e9c1fbe-179f-462e-a3ca-9c7caa41ffab.gif)

Few issues though: 
- this algorithm is slow (several minutes on a large volume). So I guess that wouldn't work when applying it during DA. But maybe we could add this step during preprocessing? Or maybe we can only apply this step during inference?
- if the denoising is too aggressive, it can "remove" a small lesion.

One way to mitigate the two arguments above is to use a less aggressive denoising filter kernel.

**Comment by uzaymacar** [comment]
Admittedly without a lot of experience with denoising, I would be in favor of introducing it during data augmentation in training to help the model generalize to noised and de-noised images. It makes more sense to leave the decision whether to apply denoising or not beforehand during inference to the user as denoising can be helpful or harmful depending on the image content.

We have already implemented [random blur in ivadomed](https://github.com/ivadomed/ivadomed/pull/1034) and use it in this project as a smoothing operator. If the goal of the denoising mentioned here is to smooth + preserve edge-information, we could perhaps implement [bilateral filtering](https://en.wikipedia.org/wiki/Bilateral_filter) in ivadomed as well (which I'm guessing can be faster than `sct_maths -denoise`)?

**Comment by jcohenadad** [comment]
blurring is quite different than denoising, and IIUC bilateral filtering is a vanilla of blurring. I could be wrong thought, so maybe worth investigating? (esp if, as you said, it should be way faster than sct_maths denoise)

**Comment by uzaymacar** [comment]
I think this is an interesting discussion -- I will try to investigate further and update this issue with results (trade-off between speed and performance across several algorithms)! For now, I am reading [a review on image denoising techniques](https://vciba.springeropen.com/track/pdf/10.1186/s42492-019-0016-7.pdf) and it mentions the following:

> The major challenges for image denoising are as follows: (a) flat areas should be smooth, (b) edges should be protected without blurring, (c) textures should be preserved, and (d) new artifacts should not be generated.

> Bilateral filtering [10] is widely used for image denoising.

> A pioneering work on non-local means (NLM) [38] used the weighted filtering of the NSS prior to achieve image denoising, which is the **most notable improvement for the problem of image denoising**.

I see that SCT uses a version of the non-local means (NLM) from the [documentation of SCT](https://spinalcordtoolbox.com/user_section/command-line.html#sct-maths).

**Comment by uzaymacar** [comment]
The denoising implementation based on NLM in SCT can be seen [here](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/f5aa4ce78077e44511f7e5fc923e8c2eda438ae8/spinalcordtoolbox/math.py#L278). For a 3D volume (from `sub-P001`) of size `(240, 256, 176)`, 

I observed the following runtimes with varying transformations run on my laptop:

| Transformation | Runtime |
| --------------- | ----- |
| random blur| 1 sec |
| NLM with `block_radius=5` (default in SCT) | 500 sec |
| NLM with `block_radius=5` (default in SCT) | 500 sec |

**Comment by uzaymacar** [comment]
For a 3D volume (from `sub-P001`) of size `(240, 256, 176)`, I observed the following runtimes on my laptop:

| Denoising method | Runtime (~) |
| ------------------ | ------------ |
| NLM with `block_radius=5` (default in SCT) | 500 secs |
| NLM with `block_radius=3` | 90 secs |
| NLM with `block_radius=2` | 25 secs |
| Bilateral filter | 200 secs |

Insights about the table:
* For comparison, gaussian smoothing / blurring is a common data augmentation and it takes ~1 sec to run on my laptop.
* For NLM, I used the [implementation in SCT](https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/f5aa4ce78077e44511f7e5fc923e8c2eda438ae8/spinalcordtoolbox/math.py#L278).
* Bilateral filtering was implemented using SimpleITK, specifically the `simpleITK.BilateralImageFilter()` class
* Different `block_radius` values for NLM were tried to see how much time can we gain. 

Denoising algorithms are very slow to the extent that we can't introduce them as data augmentations which supports @jcohenadad's suggestion. Yet, we can still make NLM a lot faster by reducing the `block_radius` without a lot of difference in the output.

I would like add this step as a **new preprocessing transformation** for ivadomed if possible. This will allow us to apply denoising directly within the config file and faster experiment to conclude whether denoising can help or not during training and / or testing. @jcohenadad would this be OK? Asking because this will introduce some overlap between ivadomed and SCT.

**Comment by jcohenadad** [comment]
> I would like add this step as a new preprocessing transformation for ivadomed if possible. This will allow us to apply denoising directly within the config file and faster experiment to conclude whether denoising can help or not during training and / or testing. @jcohenadad would this be OK? Asking because this will introduce some overlap between ivadomed and SCT.

I'm totally OK with this!

**Comment by jcohenadad** [comment]
I did a bit of investigations, and found good parameters:
~~~
sct_maths -i sub-P001_UNIT1_crop.nii.gz -denoise p=1,b=2 -o sub-P001_UNIT1_crop_denoised-p1b2.nii.gz 
~~~

Note: this should be run on the cropped image (for lesion segmentation).

**Comment by jcohenadad** [comment]
Can close as new GTs are now done
